# Generated by Django 4.2.1 on 2023-07-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_repo_url_project_repository_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_update',
            field=models.DateField(),
        ),
    ]
