# Generated by Django 4.2.1 on 2023-07-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repo_url',
        ),
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='resolve_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stable_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=50, null=True),
        ),
    ]
