# Generated by Django 4.2.1 on 2023-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stable_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
